#!/bin/bash
# Fetch secrets from AWS Systems Manager Parameter Store and write to .env.beta on the EC2 instance.
set -e

ENV_FILE=".env.beta"
echo "# Generated by fetch-ssm-env.sh on $(date)" > "$ENV_FILE"

# Helper function to get parameter
get_param() {
  local name=$1
  local value
  value=$(aws ssm get-parameter --region eu-north-1 --name "$name" --with-decryption --query "Parameter.Value" --output text 2>/dev/null || echo "")
  if [ -z "$value" ]; then
    echo "WARNING: Parameter $name could not be fetched (empty, missing, or unauthorized)!" >&2
    echo "MISSING_VALUE_FOR_$(echo $name | tr '/' '_' | tr '-' '_' | tr '[a-z]' '[A-Z]')"
  else
    echo "$value"
  fi
}

echo "Fetching application configuration from AWS SSM Parameter Store..."

# Fetch parameters
DB_PASSWORD=$(get_param "/studio-ops/beta/db-password")
SPRING_MAIL_USERNAME=$(get_param "/studio-ops/beta/spring-mail-username")
SPRING_MAIL_PASSWORD=$(get_param "/studio-ops/beta/spring-mail-password")
EMAIL_FROM=$(get_param "/studio-ops/beta/email-from")
EMAIL_FROM_NAME=$(get_param "/studio-ops/beta/email-from-name")
if [ -z "$EMAIL_FROM_NAME" ] || [[ "$EMAIL_FROM_NAME" == *"MISSING_VALUE"* ]]; then
  EMAIL_FROM_NAME="StudioOps Beta"
fi
FRONTEND_URL=$(get_param "/studio-ops/beta/frontend-url")
CORS_ALLOWED_ORIGINS=$(get_param "/studio-ops/beta/cors-allowed-origins")
PLATFORM_ADMIN_EMAILS=$(get_param "/studio-ops/beta/platform-admin-emails")
ADMIN_NOTIFICATIONS_ENABLED=$(get_param "/studio-ops/beta/platform-admin-notifications-enabled")
EMAIL_ENABLED=$(get_param "/studio-ops/beta/email-enabled")
BETA_WHATSAPP_ONLY=$(get_param "/studio-ops/beta/beta-whatsapp-only")

# Write to .env.beta
cat << EOF >> "$ENV_FILE"
# Database Configuration
DB_USERNAME=studioops
DB_PASSWORD=$DB_PASSWORD

# SMTP Mail Configuration
SPRING_MAIL_USERNAME=$SPRING_MAIL_USERNAME
SPRING_MAIL_PASSWORD=$SPRING_MAIL_PASSWORD
EMAIL_FROM=$EMAIL_FROM
EMAIL_FROM_NAME=$EMAIL_FROM_NAME
EMAIL_ENABLED=$EMAIL_ENABLED

# Application Settings
FRONTEND_URL=$FRONTEND_URL
CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS
PLATFORM_ADMIN_EMAILS=$PLATFORM_ADMIN_EMAILS
ADMIN_NOTIFICATIONS_ENABLED=$ADMIN_NOTIFICATIONS_ENABLED
BETA_WHATSAPP_ONLY=$BETA_WHATSAPP_ONLY
EOF

# Set secure permissions
chmod 600 "$ENV_FILE"
echo ".env.beta successfully generated with secure file permissions."
