export const APP_VERSION = '0.0.1';

export const USER_ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  EDITOR: 'EDITOR',
} as const;

export const PROJECT_STATUSES = {
  LEAD: 'LEAD',
  CONFIRMED: 'CONFIRMED',
  SCHEDULED: 'SCHEDULED',
  SHOOT_COMPLETED: 'SHOOT_COMPLETED',
  POST_PRODUCTION: 'POST_PRODUCTION',
  DELIVERED: 'DELIVERED',
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',
} as const;

export const EVENT_STATUSES = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const EMPLOYEE_STATUSES = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE',
} as const;

export const ASSIGNMENT_STATUSES = {
  PROPOSED: 'PROPOSED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const DELIVERABLE_STATUSES = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CLIENT: 'WAITING_FOR_CLIENT',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  REVISION_REQUIRED: 'REVISION_REQUIRED',
  DELIVERED: 'DELIVERED',
  COMPLETED: 'COMPLETED',
} as const;

export const BACKUP_STATUSES = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
} as const;

export const BACKUP_LOCATION_TYPES = {
  EXTERNAL_HARD_DRIVE: 'EXTERNAL_HARD_DRIVE',
  LOCAL_NAS: 'LOCAL_NAS',
  CLOUD_S3: 'CLOUD_S3',
} as const;
